name: C/C++ CI

on:
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
       yum install -y libstdc++-devel.i686
    
    - name: Build release
      run: |
        # Note: I set GCC 3.4 as the default compiler because newer versions don't work with some metamod versions
        cd dlls
        make
        cd $GITHUB_WORKSPACE

        mkdir bugfixedhl-linux
        mkdir -p bugfixedhl-linux/dlls

        cp -i dlls/hl_i386.so bugfixedhl-linux/dlls/hl.so
        cp -i network/delta.lst bugfixedhl-linux
        cp -i Readme.txt bugfixedhl-linux

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bugfixedhl-linux
        path: bugfixedhl-linux/
