name: C/C++ CI

on:
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        # Install 32 bits libraries
        sudo apt-get install -y gcc-multilib g++-multilib
        sudo apt-get install -y build-essential
        sudo apt-get install -y libc6-dev libc6-dev-i386

    - name: Build release
      run: |
        make -C /dlls

    - name: Distribute files
      run: |
        mkdir bugfixedhl-linux
        mkdir -p bugfixedhl-linux/dlls

        cp -i dlls/hl_i386.so bugfixedhl-linux/dlls/hl.so
        cp -i network/delta.lst bugfixedhl-linux
        cp -i Readme.txt bugfixedhl-linux

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bugfixedhl-linux
        path: bugfixedhl-linux/

  build-windows:
    runs-on: windows-2019
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
        
    - name: Build release
      run: |
        msbuild multiplayer.sln -target:hl /p:Configuration=Release

        mkdir bugfixedhl-windows
        mkdir bugfixedhl-windows\dlls

        copy dlls\msvc\Release\hl.dll bugfixedhl-windows\dlls\
        copy network\delta.lst bugfixedhl-windows
        copy Readme.txt bugfixedhl-windows
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bugfixedhl-windows
        path: bugfixedhl-windows
