name: C/C++ CI

on:
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: onlyrtxa/centos7-gcc4:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
        
    - name: Build release
      run: |        
        make -C dlls

        mkdir bugfixedhl-linux
        mkdir -p bugfixedhl-linux/dlls

        cp -i dlls/hl_i386.so bugfixedhl-linux/dlls/hl.so
        cp -i network/delta.lst bugfixedhl-linux
        cp -i Readme.txt bugfixedhl-linux

    - name: Get current tag and commit SHA for artifact naming
      id: naming
      run: |
        echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bugfixedhl-${{ steps.naming.outputs.tag }}-linux-${{ steps.naming.outputs.sha_short }}
        path: bugfixedhl-linux/

  build-windows:
    runs-on: windows-2019
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Build release
      run: |
        msbuild multiplayer.sln -target:hl /p:Configuration=Release

        mkdir bugfixedhl-windows
        mkdir bugfixedhl-windows\dlls

        copy dlls\msvc\Release\hl.dll bugfixedhl-windows\dlls\
        copy network\delta.lst bugfixedhl-windows
        copy Readme.txt bugfixedhl-windows

    - name: Get current tag and commit SHA for artifact naming
      id: naming
      run: |
        echo "tag=$(git describe --tags --abbrev=0)" >> $Env:GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $Env:GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bugfixedhl-${{ steps.naming.outputs.tag }}-win32-${{ steps.naming.outputs.sha_short }}
        path: bugfixedhl-windows
